/*
 *  Program to Check if a Number is Positive or Negative Using Relational Operator
 */ 
public class NumberPositiveNegativeExample {
    public static void checkPosOrNegNum(integer num){
        if(num>0){
            System.debug('The number is positive.');
        }else if(num<0){
            System.debug('The number is negative');
        }else{
            System.debug('The number is zero.');
        }
    }
}