/*
*  Author           : Rajesh Kumar @infosys.com
*  Description      : Test class of PrintRightRotateArray
*  Created Date     : 27-Aug-22
*  LastModifiedDate : 
*  Change Logs#     : Creating a test class for increase the code coverage
*/
@isTest
public with sharing class PrintRightRotateArray_Test {
    @isTest
    public static void test() {
        Test.startTest();
        PrintRightRotateArray  arr = new PrintRightRotateArray();
        Test.stopTest();
    }
}