public class Student {
    public  String firstName {get;set;}
    public  String lastName {get;set;}
    public  String myCity {get;set;}
    
    /*
    String one = JSON.serialize(10);
    System.debug('One = ' + one);
    Account acc = new Account(name='Wipro',Rating='Hot');
    String two = JSON.serialize(acc);
    System.debug('Account =' +two);
    Student st = new Student();
    st.firstName = 'Rajesh';
    st.lastName = 'Kumar';
    st.myCity = 'Bhinmal';
    String three = JSON.serialize(st);
    System.debug('Student =' + three);
    Contact con = [select id,name,lastname from contact limit 1];
    String four = JSON.serialize(con);
    System.debug('Contact =' +con);

    */
}